### ISSUE TITLE
HttpServerResponse#toSubscriber doesn't work correctly 

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-rx#220]
### Version

4.0.0-SNAPSHOT

### Context

When I tried to respond on a http request with a `Flowable` of `Buffer` i figured out that `HttpServerResponse#toSubscriber` might not work correctly. `end()` is not called after stream completion

### Do you have a reproducer?

The reproducer is here: https://github.com/Sammers21/vertx-rxhttp-repoducer

Execution log at Github Actions: https://github.com/Sammers21/vertx-rxhttp-repoducer/runs/441503007?check_suite_focus=true#step:5:30

### Steps to reproduce

Follow instructions in the README file

**Comment by tsegismont** [comment]
This happens because the response is not set to chunked mode.

Update the code to: 

`subscribe(request.response().toSubscriber().onError(Throwable::printStackTrace)`

You will see this in the output:

`java.lang.IllegalStateException: You must set the Content-Length header to be the total size of the message body BEFORE sending any data if you are not using HTTP chunked encoding.`

**Comment by tsegismont** [comment]
I just realized there is a bug in #219: we should test if the `WriteStream` end or error handler is null before invoking it

**Comment by tsegismont** [comment]
@Sammers21 closing this one as invalid but I will fix the issue mentioned above in all branches.

**Comment by Sammers21** [comment]
@tsegismont , good
